rustyhorde/vergen

src/constants.rs
src/lib.rs
src/output/codegen.rs
src/output/mod.rs

feat: add branch name

---

.travis.yml

Attempt to fix code coverage in travis.

Attempt to fix code coverage in travis

---

Cargo.toml
src/lib.rs

Some docs updates in `Cargo.toml` and `lib.rs`

some docs updates I missed

---

Cargo.toml
README.md

* Some minor docs update
* Version bump

Some minor doc updates, no functionality changed

---

Cargo.toml
src/constants.rs
src/lib.rs

* Release 4.1.0
* Updating some documentation

Release 4.1.0

---

Cargo.toml

`rustc_version` to 0.3.1

---

.github/workflows/main.yml
src/feature/build.rs
src/feature/cargo.rs
src/feature/git.rs
src/feature/rustc.rs
src/feature/si.rs
src/gen.rs

* Added the ability to turn off a feature programmatically.
Fixes #64

Added `enabled` flag to feature config, to turn off feature programmatically

---

src/feature/git.rs
src/gen.rs

* Added support for a configurable `-dirty` flag on the VERGEN_GIT_SEMER* output
Fixes #59

Added support for a configurable '-dirty' flag 

---

src/lib.rs

Thanks for the awesome crate!
Just installed it for a CLI I was working on, so thanks for all the hard work!
After getting it installed I realized I was a major version behind (upgrade was painless tho!) because I copy pasted this line from the docs which still referenced the older version number

Update Cargo.toml install docs for latest version

---

.github/workflows/main.yml
.vscode/settings.json
README.md
run_all.fish
vergen-pretty/Cargo.toml
vergen-pretty/src/lib.rs
vergen-pretty/src/pretty/feature/mod.rs
vergen-pretty/src/pretty/feature/serde.rs
vergen-pretty/src/pretty/feature/trace.rs
vergen-pretty/src/pretty/mod.rs
vergen-pretty/src/pretty/prefix.rs
vergen-pretty/src/pretty/suffix.rs
vergen-pretty/src/utils.rs
vergen-pretty/tarpaulin.toml

v0.1.1 vergen-pretty

---

vergen/Cargo.toml
vergen/src/feature/si.rs

v8.0.0-beta.2

---

vergen/src/utils.rs
vergen/tests/git_output.rs

* If an override environment variable is set, always use that value.

Added support for overrides when setting default values

---

vergen/Cargo.toml

Updated 'git2-rs' dependency

---

vergen-pretty/Cargo.toml
vergen/Cargo.toml

* Sync dependencies to latest versions

Dependency Sync

---

.github/workflows/main.yml
vergen/src/emitter.rs

for use in build.rs.
Fixes #188

Add ability to export VERGEN variables as environment variables

---

.github/workflows/audit.yml
.github/workflows/main.yml
.vscode/settings.json
run_all.fish
vergen-pretty/Cargo.toml
vergen-pretty/src/header/mod.rs
vergen-pretty/src/lib.rs
vergen-pretty/tarpaulin.toml

* Added support for header generation to `vergen-pretty`

Added header support to vergen-pretty

---

vergen-pretty/tarpaulin.toml

* Added a test set of features to tarpaulin for more complete coverage.

Added some coverage for tarpaulin

---

vergen/Cargo.toml
vergen/src/emitter.rs
vergen/tests/build_output.rs
vergen/tests/cargo_output.rs
vergen/tests/git_output.rs
vergen/tests/rustc_output.rs
vergen/tests/sysinfo_output.rs

* Added `disable_*` function to `EmitBuilder` to allow disabling output even if feature is enabled.
Fixes #201

Added ability to disable output even if feature is enabled

---

vergen/Cargo.toml
vergen/src/feature/git/cmd.rs

Bug fix for git log timestamp output parsing

---

run_pretty.fish
vergen-pretty/Cargo.toml
vergen-pretty/src/header/mod.rs
vergen-pretty/src/lib.rs
vergen/src/feature/cargo.rs

* More work on the `vergen-pretty` header API

(vergen-pretty) Updated header API for more convenience

---

.github/workflows/main.yml

Updated the binstall dependency to latest in `main.yml`

binstall 0.22.0 => 0.23.1

---

.github/workflows/main.yml
vergen-pretty/src/lib.rs
vergen/src/lib.rs

* Removed `unknown_diagnostic_attributes` lint.

Fixed unknows nightly lint issue

---

vergen/src/lib.rs

Fixes the error reported here https://docs.rs/crate/vergen/8.2.5/builds/909730

Fix docsrs build failure

---

vergen/Cargo.toml
vergen/src/lib.rs

Update top-level docs with more relevant examples

---

vergen/Cargo.toml
vergen/src/feature/si.rs

Add support for `RefreshKind` to the `sysinfo` feature

---

repo_util/src/repo/mod.rs
vergen/src/feature/git/cmd.rs
vergen/src/feature/git/git2.rs
vergen/src/feature/git/gix.rs
vergen/tests/git_output.rs

* Added shallow clone support to `TestRepos`
* Added check for shallow clone to `gix`
Fixes #250

Add support for shallow clones

---

vergen/Cargo.toml
vergen/src/constants.rs
vergen/src/feature/cargo.rs
vergen/src/key.rs
vergen/src/lib.rs
vergen/tests/cargo_output.rs
vergen/tests/git_output.rs

initial implementation of VERGEN_CARGO_DEPENDENCIES

---

.github/workflows/main.yml
README.md
run_all.fish
vergen/Cargo.toml
vergen/src/feature/git/mod.rs
vergen/src/lib.rs
vergen/tests/git_output.rs

Use `cfg-if` to support the feature unification from cargo

cargo feature unification support

---

README.md
vergen/src/lib.rs

Fix incorrect docs

---

MIGRATING_v8_to_v9.md
README.md
vergen-git2/Cargo.toml
vergen-git2/src/lib.rs
vergen-gitcl/Cargo.toml
vergen-gitcl/src/lib.rs
vergen-gix/Cargo.toml
vergen-gix/src/lib.rs
vergen-lib/Cargo.toml
vergen-lib/src/keys.rs
vergen-pretty/Cargo.toml
vergen-pretty/build.rs
vergen-pretty/src/lib.rs
vergen-pretty/src/pretty/mod.rs
vergen-pretty/src/utils.rs
vergen/Cargo.toml
vergen/src/lib.rs

* Updated some re-exports of `vergen-lib` structs to make usage of `AddCustomEntries` more clean.
* Documentation updates
* Updated `vergen-pretty` to work with custom key/value pairs.
* Added a new `vergen-pretty-env` macro to assist with the above.

Version 9 Beta 1

---

README.md
vergen-pretty/Cargo.toml
vergen-pretty/build.rs
vergen-pretty/src/lib.rs

* Fixes for `vergen-pretty` using `vergen-gix` build dependency.

Version 9 Beta 2

---

.github/FUNDING.yml
.github/workflows/main.yml
.vscode/settings.json
run_all.fish
run_clippy.fish
run_docs.fish
test_util/Cargo.toml
vergen-git2/Cargo.toml
vergen-gitcl/Cargo.toml
vergen-gix/Cargo.toml
vergen-lib/Cargo.toml
vergen-pretty/Cargo.toml
vergen-pretty/build.rs
vergen/Cargo.toml
vergen/src/lib.rs

* Updated some documentation
* Script tweaks
* Updated the `emit_and_set` feature to work properly with all libraries

v9-beta.2: docs tweaks, feature update, script updates

---

.github/workflows/main.yml
.github/workflows/tier2.yml

* Remove tier2 concurrency group

remove tier2 concurrency gruop

---

.github/workflows/main.yml
.github/workflows/tier2.yml
side_load/Cargo.toml
vergen-git2/src/lib.rs
vergen-gitcl/src/lib.rs
vergen-gix/src/lib.rs
vergen-pretty/src/header/mod.rs
vergen/src/lib.rs

Tier 2 Workflow

---

.github/workflows/main.yml
test_util/Cargo.toml
vergen-git2/Cargo.toml
vergen-gitcl/Cargo.toml
vergen-gix/Cargo.toml
vergen-lib/Cargo.toml
vergen-pretty/Cargo.toml
vergen/Cargo.toml

Workflow Tweaks

---

test_util/src/lib.rs
vergen-git2/src/lib.rs
vergen-gitcl/src/lib.rs
vergen-gix/src/lib.rs
vergen-lib/src/lib.rs
vergen-pretty/src/lib.rs
vergen/src/lib.rs

fixed lint issues

---

test_util/src/lib.rs
vergen-git2/src/lib.rs
vergen-gitcl/src/lib.rs
vergen-gix/src/lib.rs
vergen-lib/src/lib.rs
vergen-pretty/src/lib.rs
vergen/src/lib.rs

Fix lint issue

---

test_util/src/lib.rs
vergen-git2/src/lib.rs
vergen-gitcl/src/lib.rs
vergen-gix/src/lib.rs
vergen-lib/src/lib.rs
vergen-pretty/src/lib.rs
vergen/src/lib.rs

fixed lint issue

---

.github/workflows/pretty.yml

testing workflow chain

---

.github/workflows/pretty.yml
.github/workflows/vergen.yml
.github/workflows/vergen_lib.yml

serialize the workflows

---

test_util/Cargo.toml
vergen-gix/Cargo.toml

Updated gix to 0.60.0

---

.github/workflows/pretty.yml
.github/workflows/vergen.yml
.github/workflows/vergen_lib.yml
README.md
test_util/Cargo.toml
vergen-git2/Cargo.toml
vergen-gitcl/Cargo.toml
vergen-gix/Cargo.toml
vergen-lib/Cargo.toml
vergen-pretty/Cargo.toml
vergen/Cargo.toml

MSRV to 1.73.0

---

vergen-git2/Cargo.toml
vergen-gitcl/Cargo.toml
vergen-gix/Cargo.toml
vergen-lib/Cargo.toml
vergen-pretty/Cargo.toml
vergen/Cargo.toml

Preparation for release

---

README.md
vergen-git2/Cargo.toml
vergen-gitcl/Cargo.toml
vergen-gix/Cargo.toml
vergen-lib/Cargo.toml
vergen/Cargo.toml

* version bump for `vergen-lib`
* README updates
Fixes #350

README updates

---

vergen/src/lib.rs

Fix link in doc

---

test_util/src/lib.rs
vergen-git2/src/lib.rs
vergen-gitcl/src/lib.rs
vergen-gix/src/lib.rs
vergen-lib/src/lib.rs
vergen-pretty/src/lib.rs
vergen/src/lib.rs

Removed lint that was converted to a hard error

Removed lint that was converted to a hard error

---

vergen-git2/src/git2/mod.rs

Fixes: https://github.com/rustyhorde/vergen/issues/374

Emit fully resolved path for Git ref

---

test_util/Cargo.toml
vergen-git2/Cargo.toml
vergen-gitcl/Cargo.toml
vergen-gix/Cargo.toml
vergen-lib/Cargo.toml
vergen-pretty/Cargo.toml
vergen/Cargo.toml
vergen/src/feature/si.rs

* Updated `git2-rs` to `0.20.0`
* Updated `gix` to `0.69.1`
* Various other minor version bumps
Fixes #393

Dependency updates

---

vergen/Cargo.toml
vergen/build.rs
vergen/src/lib.rs

Added back coverage_attribute feature for coverage

---

test_util/Cargo.toml
vergen-git2/Cargo.toml
vergen-gitcl/Cargo.toml
vergen-gix/Cargo.toml
vergen-pretty/Cargo.toml
vergen/Cargo.toml

Update to latest `gix` for rustsec update.

Updated to latest deps to clear rustsec from gix

---

vergen-gix/Cargo.toml
vergen-gix/src/gix/mod.rs
vergen-gix/tests/git_output.rs

Modified from https://github.com/rustyhorde/vergen/issues/405#issuecomment-2756712125 with the original author correctly attributed. I've added some missing implementation details and tests modified from `vergen-git2`.
Fixes #405

Implement dirty for gix

---

vergen-gitcl/src/gitcl/mod.rs

Attempt to fix the pattern match command on windows

---

vergen-gix/src/gix/mod.rs

Fix dirty output for `vergen-gix`

---

vergen-gitcl/Cargo.toml
vergen-gitcl/src/gitcl/mod.rs
vergen-gix/Cargo.toml

Only check for contains "true" on worktree check

---

.github/workflows/audit.yml
.github/workflows/vergen.yml
test_util/src/lib.rs
vergen-git2/src/git2/mod.rs
vergen-git2/src/lib.rs
vergen-gitcl/src/gitcl/mod.rs
vergen-gitcl/src/lib.rs
vergen-gix/src/gix/mod.rs
vergen-gix/src/lib.rs
vergen-lib/Cargo.toml
vergen-lib/src/emitter.rs
vergen-lib/src/lib.rs
vergen-pretty/src/lib.rs
vergen/src/feature/cargo.rs
vergen/src/lib.rs

* Update the `rustc` lints to the lastest
* Fix lint issues that arose as a result.

Updated lints and lint fixes

---

vergen-pretty/Cargo.toml

* version bump for `vergen-pretty`

vergen-pretty: 1.0.1 -> 1.0.2

---

test_util/Cargo.toml
test_util/src/lib.rs
vergen-git2/Cargo.toml
vergen-git2/src/lib.rs
vergen-gitcl/Cargo.toml
vergen-gitcl/src/lib.rs
vergen-gix/Cargo.toml
vergen-gix/src/lib.rs
vergen-lib/Cargo.toml
vergen-lib/src/lib.rs
vergen-pretty/Cargo.toml
vergen-pretty/src/lib.rs
vergen/Cargo.toml
vergen/src/lib.rs

Removed feature and bumped versions in preparation for releases

removed docs_auto_cfg and bumped versions
