rustyhorde/vergen

README.md

Since the upgrade the function `OutputFns` does not exist anymore and has been replaced with the `ConstantsFlags` function.

Fix README to use ConstantsFlags function in build.rs example

---

src/lib.rs

Update the crate version in the example.
Use `flags` variable that is created. Otherwise this variable is useless and produce a compiler warning.

Update doc example

---

src/output/mod.rs

Currently, even when there is no `.git` and the git command fails, we still get empty env vars instead of `UNKNOWN` because vergen forgets to check the return code.
This PR fixes that, to only return stdout if the command reported success.

properly detect failed commands

---

Cargo.toml
src/output/codegen.rs
src/output/envvar.rs
src/output/mod.rs

The `failure` crate is kinda deprecated and superseded by many other crates.
And boxed `std::error::Error` is feasible for vergen.
On a side note `failure_derive` breaks the build of many crates because of the use of a "private" type in `quote`.
https://users.rust-lang.org/t/failure-derive-compilation-error/39062

Replace `failure` with boxed `std::error::Error`

---

Cargo.toml
README.md
src/constants.rs
src/output/mod.rs

This PR adds compiler version information courtesy of [`rustc_version`](https://crates.io/crates/rustc_version).
For example, this makes the following possible:
```
/// Application version string. Sample:
///
/// application 0.0.1
///
/// Built from commit 9510c567d23dd80c4b0d44ff6e63d332868c2de1 at 2020-05-09T18:29:10.402031601+00:00 with rustc 1.43.1 stable for x86_64-unknown-linux-gnu on x86_64-unknown-linux-gnu.
let version = concat!(
env!("VERGEN_SEMVER"), "\n\nBuilt from commit ", env!("VERGEN_SHA"), " at ", env!("VERGEN_BUILD_TIMESTAMP"),
" with rustc ", env!("VERGEN_RUSTC_SEMVER"), " ", env!("VERGEN_RUSTC_CHANNEL"), " for ", env!("VERGEN_TARGET_TRIPLE"),
" on ", env!("VERGEN_HOST_TRIPLE"), "."),
```

Add compiler version information

---

src/output/envvar.rs

Fixes a harmless bug where vergen outputs an extra newline after the 'cargo:rerun-if-changed={branch}' line.

Trim newlines from .git/HEAD contents

---

src/constants.rs
src/lib.rs
src/output/mod.rs

By default, '-dirty' will be added the the SHA and SHORT_SHA environment variables if the build has run on a directory with uncommitted changes.   This behavior can be toggle off via the `TAG_DIRTY` flag.
Fixes #25

Added support for 'TAG_DIRTY' flag, to add '-dirty' to the SHA variables

---

src/output/envvar.rs
src/output/mod.rs

Added command to properly determine the base git directory to be used within `generate_cargo_keys`.
Fixes #21

Added command to determine properly the git base directory

---

Cargo.toml
README.md
src/lib.rs

* Updated README.md with 4.0.0 breaking changes.
* Updated lib.rs with some additional information.
* Updated Cargo.toml.
* Fixes #15

Prepare release 4.0.0

---

.github/workflows/main.yml

In #37 it looked like GitHub Actions is currently not running for pull requests. This PR fixes the problem by slightly adjusting the workflow config.

Enable CI for pull requests

---

Cargo.toml

This fixes #36 by disabling the `git2` features that rely on `openssl-sys`, since it looks like we're not actually using any of them in this crate :)

git2: Disable default features

---

Cargo.toml

Requires `rustc_version` to be at least 0.3.1 in order to prevent the following error if another dependency uses an older version of `rustc_version`.  The `llvm_version` field on `rustc_version::VersionMeta` was added in rustc_version `0.3.1`.
```
error[E0609]: no field `llvm_version` on type `VersionMeta`
--> /home/drk/.cargo/registry/src/github.com-1ecc6299db9ec823/vergen-4.0.2/src/feature/rustc.rs:79:42
|
79 |             if let Some(llvmver) = rustc.llvm_version {
|                                          ^^^^^^^^^^^^ unknown field
|
= note: available fields are: `semver`, `commit_hash`, `commit_date`, `build_date`, `channel` ... and 2 others
error: aborting due to previous error
For more information about this error, try `rustc --explain E0609`.
error: could not compile `vergen`
``` …

fix: Require rustc_version ^0.3.1

---

Cargo.toml
src/config.rs
src/constants.rs
src/feature/cargo.rs
src/feature/mod.rs
src/gen.rs
src/lib.rs

* There are a handful of cargo variable that are only set a environment variables for build scripts (https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts).  This features writes vergen cargo instructions for the target triple, the profile, and enable features.

Added a `cargo` feature to expose some cargo env variable

---

.clippy.toml
README.md
src/config.rs
src/constants.rs
src/feature/build.rs
src/feature/cargo.rs
src/feature/git.rs
src/feature/mod.rs
src/feature/rustc.rs
src/gen.rs
src/lib.rs

* Deprecated `gen` and `ConstantsFlags` (will remove in version 5).
* Added `Config` to control instruction generation.  The bitflags were getting out of hand so switching to the `Config` pattern seemed prudent.
* Added support for timezone specification on the various date/time outputs (Utc and Local supported).
* Added support for various date/time/timestamp output combinations to suit different needs.

Replace `ConstantsFlags` with `Config`

---

Cargo.toml

* `gen` -> `vergen`.   Deprecated the `gen` entrypoint.
* `ConstantsFlags` -> `Config`.  Deprecated the `ConstantsFlags`.
* `ConstantsFlags` were getting bloated, so created `Config`.

Release v4.2.0

---

Cargo.toml

A number of the versions in Cargo.toml were pretty loose (e.g. `"0"`) and I was fairly sure that at least some of them weren't accurate (I knew that `serial_test` almost certainly wasn't). A bit of experimentation later, I've found a series of them that didn't work with the lowest versions that were valid for the listed ranges, and inserted some more precise ranges (while still trying to keep the flexibility where valid).
In theory this could be automatically tested with `cargo +nightly build  -Z minimal-versions` but you end up with issues like early versions of `libssh2-sys` having hyphenated names and having to add a bunch of extra "no, not that version" checks to make it work sadly.

Make some loose versions in Cargo.toml slightly more accurate

---

Cargo.toml
src/config.rs
src/constants.rs
src/error.rs
src/feature/mod.rs
src/feature/si.rs
src/gen.rs
src/lib.rs

* Add `sysinfo` feature to allow access to machine specific data that may be useful as build time data

Add `sysinfo` support

---

src/feature/cargo.rs

The value of CARGO_FEATURE_* environment variable in build scripts is
"1". Thus a value of VERGEN_CARGO_FEATURES becomes something like
"1,1,1".
This commit fixes the 'is_cargo_feature' function to return the feature
name, as it appears in the CARGO_FEATURE_ environment variable name,
instead of the environment variable value, which is constant "1".

fix VERGEN_CARGO_FEATURES

---

src/config.rs
src/feature/git.rs
src/lib.rs

* Added documentation for `VERGEN_GIT_SHA_SHORT` env variable.
* Added documentation for `VERGEN_GIT_SEMVER_LIGHTWEIGHT` env variable.
Fixes #68

Updated git docs to include SHA_SHORT and SEMVER_LIGHTWEIGHT

---

src/feature/git.rs

I noticed that vergen is causing my rust project to always rebuild, and I traced it down to a `rerun-if-changed` directive that points to a nonexistent file. 
This causes `cargo` to assume that the file was just deleted and needs to rebuild. With this patch, we only emit `rerun-if-changed` if the files actually exist.
I've tested this by wiring it up to my project and it fixes the constant rebuild problem.

Check whether files exist before emitting `rerun-if-changed` directive

---

Cargo.toml

With default features sysinfo will pull in rayon, which isn't very nice for build times.
build.rs scripts aren't supposed to use more than one CPU anyway, see https://doc.rust-lang.org/cargo/reference/build-scripts.html#jobserver

Disable the Rayon dep for sysinfo

---

src/feature/rustc.rs

Occasionally `rustc -vV` (used by `rustc_version`) will return `unknown`
for the commit date and/or hash. In `rustc_version::VersionMeta`, this
is represented as a `None` value in the `commit_hash` and `commit_date`
fields. This is a problem if these variables are depended on by the
application, as vergen will not panic if they are not present, but will
instead silently omit them.
This PR fixes this issue by replacing a `None` value for a commit hash
or date with the string "unknown".
Fixes #78

Replace rustc commit hash/date when not present

---

Cargo.toml

* Pin `sysinfo` to 0.19
Fixes #80

Pin `sysinfo` to the lowest supported version

---

src/lib.rs

We couldn't determine `Result` is `anyhow::Result` from rendered documentation. It's little confusing.
https://docs.rs/vergen/5.1.13/vergen/

fix little confusing build.rs in documentation comment

---

build.rs
src/lib.rs

* `beta` and `stable` release recently so updated lints matrix to reflect.

Updated lints

---

Cargo.toml

A default feature in Chrono pulls in `time` v0.1, which is completely unnecessary for this crate, and on top of that currently it's marked by rustsec as vulnerable and unfixable.

Don't require old time dependency

---

src/feature/git.rs

I needed to have both variants available, so I added a new `ShaKind::Both` kind that outputs them both.

Add ShaKind::Both to output both normal and short variants

---

build.rs

Before and since have to use the same version, right now 1.57 is excluded so it
cannot find msrv_lints().
Fixes #105

Fix msrv_lints version

---

Cargo.toml
README.md
build.rs
src/config.rs
src/feature/build.rs
src/feature/git.rs
src/feature/mod.rs
src/gen.rs

* `chrono` has been replace with `time` as the `time` crate is better maintained.
* Added a `local_offset` feature flag.  Using this will enable the local timezone features in the `git` and `build` features.  However, due to a [potential segfault](https://github.com/rustsec/advisory-db/blob/main/crates/time/RUSTSEC-2020-0071.md) in the `time` crate, you must also explicitly opt in to the unsoundness by setting `RUSTFLAGS="--cfg unsound_local_offset"`.   Per the `time` crate docs, this is untested, so use with extreme caution.

`chrono` replaced with `time`,  `local_offset` feature flag added

---

README.md

Perhaps the sponsors would prefer nine letters instead of eight.

Correct typo: tyretool -> tryretool

---

Cargo.toml
src/config.rs
src/feature/build.rs
src/feature/git.rs
src/feature/rustc.rs
src/feature/si.rs
src/gen.rs
src/lib.rs

Closes #124 
What has been done:
- Add a configuration option `skip_if_error` to the `build`, `git`, `rustc` and `sysinfo` features, to allow skipping a feature and continuing if an Error occurs. `configure_cargo` is not fallible, so the option wouldn't make sense there. 
- Emit a `cargo:warning` if an Error was skipped in this way.
- Add a test for `skip_if_error` for the `git` feature. This adds a new dependency `tempfile`, which is just needed for this one test of the `git` feature. Sadly, there is no way to define optional dev-dependencies (https://github.com/rust-lang/cargo/issues/1596), so I deactivated the `unused_crate_dependencies` lint.
- Add documentation for the option and mention `option_env!`.
- Fix two unrelated nits. 
Open questions:
-  I'm not sure if `skip_if_error` is a …

Add option to continue if an Error occurs in one section

---

Cargo.toml
LICENSE-APACHE
README.md
src/config.rs
src/constants.rs
src/error.rs
src/feature/build.rs
src/feature/cargo.rs
src/feature/git.rs
src/feature/mod.rs
src/feature/rustc.rs
src/feature/si.rs
src/gen.rs
src/lib.rs

this is a non-substantive maintenance cleanup suggestion.

use https:// for all links -- avoid legacy http://

---

Cargo.toml
src/error.rs

Hi!
`enum-iterator` `1.2.0` is using unstable features, causing some projects using vergen to fail when building:
```
error[E0658]: use of unstable library feature 'array_from_fn'
--> /root/.cargo/registry/src/github.com-1285ae84e5963aae/enum-iterator-1.2.0/src/lib.rs:554:18
|
554 |             Some(core::array::from_fn(|_| unreachable!()))
|                  ^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information
```
Thanks!

Prevent E0658 by limiting enum-iterator version.

---

src/feature/build.rs

See https://reproducible-builds.org/docs/source-date-epoch/ for details.
This enables reproducible builds.

Use `SOURCE_DATE_EPOCH` environment variable as build timestamp if set

---

src/feature/build.rs

There seems to be a typo in the documentation. There isn't such thing as `SOURCE_BUILD_EPOCH`, I think it should be `SOURCE_DATE_EPOCH`.

Fix documentation for `SOURCE_DATE_EPOCH` variable

---

src/feature/si.rs

With commit 6a2e7545feae37fab052dfe8d5d086827c0d70ab when I run "cargo test --all --all-targets --no-default-features --features build,cargo,si" I see
cargo:rustc-env=VERGEN_SYSINFO_TOTAL_MEMORY=16 GB
Which correctly reflects the ram in my system. 
However with 2bb2b49d5c0f10fb1a155f5dff3048a392d5ed1c and current master I see.
cargo:rustc-env=VERGEN_SYSINFO_TOTAL_MEMORY=16 xB
The cause of this is that sysinfo 0.16 changed the units for reporting memory from kilobytes to bytes, this commit updates the reported units to match. I also added TB to the list of possible units. Computers with terabytes of memory do exist nowadays.

Fix memory reporting with sysinfo 0.16

---

Cargo.toml

Unblocks projects that link against native libgit2 for other reasons
from being able to upgrade.

Bump libgit2 dependency to latest upstream

---

vergen/src/lib.rs

* Updated the docs to correctly refer to the `gitoxide` feature.   This was renamed during the beta.
* Updated references to the beta version to the current release version
Fixes #176

Fix documentation regarding the gitoxide feature

---

.github/workflows/main.yml
.vscode/settings.json
vergen/src/feature/git/cmd.rs
vergen/tests/git_output.rs

* By default, `git --version` will be used to check for the existence of git on the command line when using the `gitcl` feature.
* Added the ability to specify the command to use in the git `Config` via the `git_cmd` function
Fixes #175

Update git command line check to `git --version`

---

.vscode/settings.json
vergen/Cargo.toml
vergen/src/feature/git/cmd.rs
vergen/src/feature/git/git2.rs
vergen/src/feature/git/gix.rs
vergen/tests/git_output.rs

* Added `--match` support on the `git_describe` function for the `git2` and `gitcl` features (`gitoxide` seems to not support this at the moment)
Closes #157

Add `--match` support for `git_describe`

---

vergen/Cargo.toml

* Fixed issue with `gitcl` command line check.  Some versions of git do not recognize the `-v` option.   This was changed to `git --version` by default.   You can also now specify the command you wish to use to check for git in configuration.
* Updated some out of date docs referring to an old feature.
* Added the ability to specify a `match` glob string for the `git describe` output.   This is supported in the `gitcl` and `git2` features.   At this time I could not determine how to do the similar logic with `gitoxide` so this config has no effect in that feature.

Release 8.1.0

---

vergen/src/feature/git/cmd.rs
vergen/tests/git_output.rs

* Added quotes around the `--match` glob pattern.  This should work for all shells.

Added quotes to all match globs.

---

vergen/src/lib.rs

Enumerate usage steps in root crate documentation

---

vergen/Cargo.toml

* Work with `--match` on `git_describe`
* Updated environment variable overrides to work even if the generation errors.

Release 8.1.1

---

.github/workflows/main.yml

* Pin `binstall` to `0.22.0` to help alleviate the yank of `tracing 0.38.0`

Adjust to use binstall at 0.22.0

---

vergen/src/emitter.rs
vergen/src/feature/git/cmd.rs
vergen/src/lib.rs

The most significant typo in this PR is an incorrect `git` command for the timestamp.

Fix some minor typos

---

vergen/src/emitter.rs
vergen/src/feature/build.rs
vergen/src/feature/cargo.rs
vergen/src/feature/git/cmd.rs
vergen/src/feature/git/git2.rs
vergen/src/feature/git/gix.rs
vergen/src/feature/rustc.rs
vergen/src/feature/si.rs

* Skip checks when no output variables are enabled, even if feature is enabled.
Fixes #203

Add skip when no output enabled, even if feature is enabled

---

vergen/Cargo.toml
vergen/src/feature/git/gix.rs

* Updated to `gix 0.47.0`
* New `Time` struct store time since epoch differently, updated to reflect that change.

update to gix 0.47.0, fix issue caused by new Time struct

---

vergen/Cargo.toml
vergen/src/emitter.rs
vergen/src/feature/build.rs
vergen/src/feature/git/cmd.rs
vergen/src/feature/git/git2.rs
vergen/src/feature/git/gix.rs
vergen/tests/build_output.rs
vergen/tests/git_output.rs

* Updated `gix` to 0.48.0
* Added support for specifying a custom `build.rs` location.
* Added support for using a local offset for date/timestamp display.  
**NOTE** - Using a local offset will likely cause failures on Unix systems due to the [`Soundness`](
https://docs.rs/time/latest/time/util/local_offset/fn.set_soundness.html#safety) check that the `time` crate performs.  I don't want to introduce unsoundness support to `vergen`.
Fixes #214
Fixes #222

Custom build.rs path support, local time offset support, updated gix dep

---

vergen/Cargo.toml

As of 022e804, we depend on `OffsetDateTime::checked_to_offset` which was added in `0.3.22`.
Resolves #225

Bump `time` to `0.3.22`

---

vergen/Cargo.toml

Updates underlying libgit2 from `1.6.4` to `1.7.1`.
See the `git2` crate changelog [here](https://github.com/rust-lang/git2-rs/blob/git2-0.18.0/CHANGELOG.md#0180---2023-08-28).
See the libgit2 changelog [here](https://github.com/libgit2/libgit2/blob/v1.7.1/docs/changelog.md#v171).

Upgrade git2 crate to 0.18

---

vergen/Cargo.toml

It comes with fine-graned features which typically improve compile times
and reduce binary sizes.
Previously, it took 8.3s to build and produced a 3.29MB library, now it take 7.08s
to build and produces a 3.14MB binary.

update to `gix` 0.53.1

---

vergen/Cargo.toml
vergen/src/emitter.rs

* Version to 8.2.5
* Removed `#[doc(hidden)]` from `emit_at` function to allow repository path to be specified (fixes #230)

version bump, remove doc_hidden for emit_at

---

repo_util/src/repo/mod.rs

This only affects test code so no new release needs to be created.

Remove commented out remove in drop for TestRepos

---

vergen/src/emitter.rs

Fixes #249
This removes any newlines from output intended for cargo instructions.   At some point, I may extend this to encode the newlines.   However, this would require some utility to decode the environment variables when they are used.

Filter newlines from cargo instruction output

---

test_util/src/repo/mod.rs
vergen-gix/src/gix/mod.rs
vergen-gix/tests/git_output.rs

This PR updates the `vergen-gix` crate to consider lightweight tags in a git repository when emitting the describe output, depending on the value of the `tags` parameter provided. This fixes the issue reported in https://github.com/rustyhorde/vergen/issues/359#issuecomment-2262199534. This PR also updates the test repo creation code to create a lightweight tag, and adds a test case in the `vergen-gix` crate.
While working on this PR, I noticed that the `vergen-gix` crate does not consider the `matches` parameter, I've opened #363 so that it's documented for other users of the crate.

Consider lightweight tags in `GixBuilder::describe()` based on `tags`

---

vergen-lib/Cargo.toml
vergen-lib/src/emitter.rs
vergen-lib/src/entries.rs
vergen/Cargo.toml
vergen/src/feature/cargo.rs

Unfortunately, [`proc-macro-error`'s use via `getset` triggers `cargo audit`](https://rustsec.org/advisories/RUSTSEC-2024-0370). #358 already removed `getset`, but missed some `cargo +nightly clippy` findings.
This PR builds upon #358 and fixes all lints.
Fixes #371 and #373.

Remove proc-macro-error by removing getset

---

vergen-gitcl/src/gitcl/mod.rs

Hello, and thanks a bunch for this awesome crate!
This patch makes any `git` commands in the `vergen-gitcl` subcrate log their stdout/stderr on failure to provide more background.
I've just wasted a couple of hours debugging `vergen` telling me that it was "`not within a suitable 'git' worktree!`" when it clearly was...
The root cause of the issue turned out to be that the `rust-build.action` I was using had "dubious ownership" on the `.git` directory, as it is a container-based GitHub action where the `$GITHUB_WORKSPACE` is bind-mounted within the container and thus has differing user IDs.
The effect of this was that some `git` subcommands (most notably `rev-parse`) would error out like so:
```
$ git rev-parse --is-inside-work-tree
fatal: detected dubious ownership in repository at …
```

gitcl: log output of failed `git` commands.

---

test_util/src/repo/mod.rs
vergen-git2/src/git2/mod.rs
vergen-gitcl/src/gitcl/mod.rs
vergen-gix/src/gix/mod.rs

`git status` (and `git describe --dirty`) takes an optional write lock as a performance optimization: https://git-scm.com/docs/git-status#_background_refresh
This is bad because:
- Other processes might run at the same time, try to acquire the lock, and fail.
- The child process can get killed for a variety of reasons, and may not be able to clean up the lock, leading to later errors about stale lockfiles.
Both of these situations are very hard to root cause and debug.
`git describe` does not currently support `GIT_OPTIONAL_LOCKS=0` (https://github.com/gitgitgadget/git/pull/1872), so this reimplements the `-dirty` suffix logic using `git status`.
This is not an issue for libgit2 or gix, but this includes tests for those backends in case they change their implementations.

git: Ensure no backend ever takes an index lock

---

vergen-git2/src/git2/mod.rs
vergen-git2/src/lib.rs
vergen-git2/tests/git_output.rs
vergen-gitcl/src/gitcl/mod.rs
vergen-gitcl/tests/git_output.rs
vergen-gix/src/gix/mod.rs
vergen-gix/tests/git_output.rs
vergen-lib/src/emitter.rs
vergen-lib/src/entries.rs
vergen-lib/src/utils.rs
vergen/src/feature/build.rs
vergen/src/feature/cargo.rs
vergen/src/feature/rustc.rs
vergen/src/feature/si.rs
vergen/tests/cargo_output.rs

* Update the default behavior to emit warnings when a variable cannot be emitted, rather than the current behavior of defaulting to the idempotent output.
* The `idempotent` configuration can still be used to generate all output with the idempotent default, unless `fail_on_error` is specified.

Default to warnings
